---
abstract: 'Moose minus the antlers'
author:
  - 'Shawn M Moore, C<< <sartak at gmail.com> >>'
build_requires:
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Mouse
no_index:
  directory:
    - inc
    - t
requires:
  Class::Method::Modifiers: 1.00
  MRO::Compat: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  perl: 5.6.0
version: 0.03
